### ISSUE TITLE
iOS build issues on macOs

### ISSUE THREAD

**Issue by backwards-rat-race** [EraYaN/jellyfin-webng#22]
Hi. Not sure if the issues are just for me but when running 'yarn run ios' or 'react-native run-ios' I had issues stating that the simulator cannot be ran.

After investigation I was facing this react-native bug which occurs on macOS 14;

https://github.com/facebook/react-native/issues/23282

I upgraded the react-native library to latest version in the package.json and the issue was resolved. But then faced issues with linking the binary during compilation. This required the xcode project to be changed to link the javascript iOS framework.

Have/are others running this on iOS without issues?
I have committed fixes for the above issues on my fork and I will add a pull request for this issue if the changes want to be merged in.

**Comment by d3vhound** [comment]
I've been running into this issue all day. I think it has something to do with downloading the xcode beta 10.3, never had this issue until then and reinstalling Xcode doesn't seem to work. I guess I'm stuck with this issue.

**Comment by backwards-rat-race** [comment]
The changes in the pull request (upgrading to newest react) fixed the issue for me. There’s a few pointers on that linked react-native issue about changing how it recognises the simulator names that might help if the upgrade doesn’t maybe?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by anthonylavado** [comment]
Ran this, seems to work in at least XCode 10.2.1, which I have on macOS 10.14.5. Moving to close for now, as I've merged #23.
