### ISSUE TITLE
Switch JS to TypeScript

### ISSUE THREAD

**Issue by comassky** [EraYaN/jellyfin-webng#25]
Hi everyone,

I think it may be a good decision to switch to Typescrypt (typed data, some optimisations etc etc).

More industrial way to code.

**Comment by ghost** [comment]
Big mistake not to use typescript.... makes code a lot more maintainable and the dev experience is so much better than JS.

**Comment by anthonylavado** [comment]
If this is desired (and will help improve the client), then we just need someone to implement it :-)

**Comment by EraYaN** [comment]
There are some dependencies that blocked this when I first tried it, and I didn't feel like digging into tsc's options too much. But if anyone wants to have a go, please.
