### ISSUE TITLE
Is it true that the PC and mobile isomorphisms are feasible?

### ISSUE THREAD

**Issue by fhyoga** [EraYaN/jellyfin-webng#36]
The goal of this project, I want to say some of my own views, may be biased.
I think the mobile and PC should be divided into two projects. React Native and Electron isomorphic development may not be a good idea.
1. The RN itself is limited by the platform and sacrifices a lot of performance and interactive experience for code isomorphism. This also makes PC-side applications unable to achieve the best interaction.
2. For PC and mobile isomorphism, you need to write a lot of configuration, hack, and compatibility code.

Advantages of separate maintenance:
1. You can use the best interaction of your platform without having to consider how to make a platform compatible. Can reduce mental burden
2. Code quality will improve and maintenance costs will decrease
3. Potential contributors are more likely to get started, maybe this project can progress faster

My point is:

I recommend splitting into two project developments, the mobile side is based on RN implementation, and the PC side is based on Electron+React.

**Comment by EraYaN** [comment]
These problems are all academic when there are no developers. Of course native-(ish) development would be much better. But we frankly do not have the bodies to throw at it. Anyone is free to start a full React-DOM UI.
