### ISSUE TITLE
Skip ahead / behind for audio

### ISSUE THREAD

**Issue by jdmarshall90** [EraYaN/jellyfin-webng#54]
On the desktop web app, when playing my podcasts, there are skip ahead / back buttons (10 or 30 seconds, something like that). Those aren't present in this app, on an iPhone X.

I'm not sure if this is an issue with this app, or the web UI since my understanding is that this app is just a small web wrapper. If this issue should be opened on the web repo, I'd be happy to create one there instead.

**Comment by anthonylavado** [comment]
This client... isn't developed and hasn't been touched in months. What app are you using? I'll direct it to the correct repo for you.

**Comment by jdmarshall90** [comment]
I'm using [this one](https://apps.apple.com/us/app/jellyfin-mobile/id1480192618)

**Comment by anthonylavado** [comment]
Issue created here: https://github.com/jellyfin/jellyfin-expo/issues/171
