### ISSUE TITLE
I want to use jellyfin on iOS

### ISSUE THREAD

**Issue by Zxilly** [EraYaN/jellyfin-webng#9]
Did this work out?

**Comment by DeveloperOl** [comment]
For now you have to use the webapp on iOS. This app is not functional at the moment. When it gets more features it will probably be published on the appstore, i guess.

**Comment by anthonylavado** [comment]
What @DeveloperOl says is correct.

We have plans to publish on the AppStore once this is functional. Until then, the web app does play most media. If you add it to your home screen, it will act like a full app.
